config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :questions do
    resources :answers, only: [:create]
  end

 root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  validates :answer, length: {minimum: 50}
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers, dependent: :delete_all, validate: :false
  accepts_nested_attributes_for :answers

  validates :title, length: {minimum: 40}
  validates :description, length: {minimum: 150}
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  # POST answers
  def create
    @question = Question.find(params[:question_id])
    @answer = Answer.new(answer_params)
    @answer.question_id = @question.id
    @answers_chron = Answer.all.order(created_at: :desc).where(question_id: @question.id)

    if @answer.save
      redirect_to question_path(@question)
    else
      render 'questions/show'
    end
  end

  private

  #Don't trust people!
  def answer_params
    params.require(:answer).permit(:answer)

  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

    # GET /questions
  def index
    @questions = Question.all.order(created_at: :desc)
  end

  # GET /questions/1
  def show
    @question = Question.find(params[:id])
    @answer = Answer.new
    @answers_chron = Answer.all.order(created_at: :desc).where(question_id: @question.id)
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  #POST question
  def create
    @question = Question.new(question_params)

    if @question.save
      # flash[:notice] = "Your question has been submitted."
      redirect_to @question

    else
    #   flash[:notice] = "There was an error with your submission. Please try again."
      render :new
    end
  end

  #PUT question
  def edit
    @question = Question.find(params[:id])
  end

  #UPDATE new question
  def update
    @question = Question.find(params[:id])

    if @question.update(question_params)
      redirect_to @question
    else
      render 'edit'
    end
  end

  #DELETE question
  def destroy
    @question = Question.find(params[:id])
    @question.destroy

  flash[:notice] = "You have successfully deleted your question"
  redirect_to @question
  end



  private

  #Don't trust people!
  def question_params
    params.require(:question).permit(:title, :description)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def markdown(text)
  render_options = {
    # will remove from the output HTML tags inputted by user
    filter_html:     true,
    # will insert <br /> tags in paragraphs where are newlines
    # (ignored by default)
    hard_wrap:       true,
    # hash for extra link options, for example 'nofollow'
    link_attributes: { rel: 'nofollow' }
    # more
    # will remove <img> tags from output
    # no_images: true
    # will remove <a> tags from output
    # no_links: true
    # will remove <style> tags from output
    # no_styles: true
    # generate links for only safe protocols
    # safe_links_only: true
    # and more ... (prettify, with_toc_data, xhtml)
  }
  renderer = Redcarpet::Render::HTML.new(render_options)

  extensions = {
    #will parse links without need of enclosing them
    autolink:           true,
    # blocks delimited with 3 ` or ~ will be considered as code block.
    # No need to indent.  You can provide language name too.
    # ```ruby
    # block of code
    # ```
    fenced_code_blocks: true,
    # will ignore standard require for empty lines surrounding HTML blocks
    lax_spacing:        true,
    # will not generate emphasis inside of words, for example no_emph_no
    no_intra_emphasis:  true,
    # will parse strikethrough from ~~, for example: ~~bad~~
    strikethrough:      true,
    # will parse superscript after ^, you can wrap superscript in ()
    superscript:        true
    # will require a space after # in defining headers
    # space_after_headers: true
  }
  Redcarpet::Markdown.new(renderer, extensions).render(text).html_safe
end

end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/answers/index.html.erb
<h1>Answers#index</h1>
<p>Find me in app/views/answers/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RescueMission</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if flash.any? %>
  <div class="flash">
    <div class="container">
      <%= flash[:notice] %>
    </div>
  </div>
<% end %>

<%= yield %>


</body>
</html>

app/views/questions/edit.html.erb
<h2>Edit your Question</h2>

<%= form_for :question, url: question_path(@question), method: :patch do |f| %>

  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being submitted:</h2>

      <ul>
      <% @question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<h1>All Questions</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Submitted</th>
  </tr>

  <% @questions.each do |question| %>
    <tr>
      <td><%= link_to question.title, question %></td>
      <td><%= question.created_at.strftime("%H:%M")%> on <%= question.created_at.strftime("%b. %d %Y")%></td>
    </tr>
  <% end %>
</table>

<%= link_to 'Submit a Question', new_question_path %>
</br>
<%= link_to 'Home', controller: 'welcome' %>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= form_for (@question) do |f| %>

  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being submitted:</h2>

      <ul>
      <% @question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'All Questions', controller: 'questions' %>
<%= link_to 'Home', controller: 'welcome' %>

app/views/questions/show.html.erb
<h2>Question</h2>
<p>
  <strong>Title: </strong>
  <%= markdown @question.title %>
</p>

<p>
  <strong>Description: </strong>
  <%= markdown @question.description %>
</p>

<%= link_to 'Edit', edit_question_path(@question) %> <%= link_to 'Delete', question_path, method: :delete %>

<h2>Submit an Answer</h2>

<%= form_for [@question, @answer] do |f| %>

  <% if @answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being submitted:</h2>

      <ul>
      <% @answer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :answer %><br>
    <%= f.text_area :answer %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>


<h2>Answers</h2>
<table>
  <tr>
    <th>Answer</th>
    <th>Submitted</th>
  </tr>
  <% @answers_chron.each do |answer| %>
    <tr>
      <td><%= markdown answer.answer %></td>
      <td><%= answer.created_at.strftime("%H:%M")%> on <%= answer.created_at.strftime("%b. %d %Y")%></td>
    </tr>
  <% end %>
</table>



<%= link_to 'All Questions', controller: 'questions' %>
<%= link_to 'Home', controller: 'welcome' %>

app/views/welcome/index.html.erb
<h1>Rescue Mission</h1>

<%= link_to 'Submit a Question', new_question_path %>
<%= link_to 'View all Questions', controller: 'questions' %>